# Generated by Django 5.2.9 on 2026-01-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('diagnostic', 'Diagnostic'), ('psychological', 'Psychological')], max_length=50)),
                ('doctor', models.CharField(choices=[('doctor_a', 'Doctor A'), ('doctor_b', 'Doctor B')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
